ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('items.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('account/', include('allauth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

items/urls.py
from django.urls import path
from .views import (
    HomeView,
    AboutView,
    SearchCategoryView,
    ContactView,
    SearchView,
    ItemDetailView,
    add_to_cart,
    remove_from_cart,
    OrderSummeryView,
    remove_single_item_from_cart,
    Payment,
    CheckoutView,
    updateItem
)

app_name = 'items'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('category_search/<category>/', SearchCategoryView.as_view(), name='search_category'),
    path('search/', SearchView.as_view(), name='search'),
    path('order_summery/', OrderSummeryView.as_view(), name='order_summery'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add_to_cart/<slug>/', add_to_cart, name='add_to_cart'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('remove_from_cart/<slug>/', remove_from_cart, name='remove_from_cart'),
    path('remove_single_item_from_cart/<slug>/', remove_single_item_from_cart, name='remove_single_item_from_cart'),
    path('payment/<payment_option>/', Payment.as_view(), name='payment'),

    path('update_item/', updateItem, name='update_item'),

]

items/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django.template.defaultfilters import slugify
from django_countries.fields import CountryField
from django.utils import timezone
from django.db.models.signals import pre_save

from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

from embed_video.fields import EmbedVideoField

CATEGORY_CHOICES = (
    ('S', 'Shirt'),
    ('P', 'Pants'),
    ('J', 'Jeans'),
    # ('Swtrs', 'Sweaters'),
    ('J&C', 'Jacket and Coats'),
    ('T&Tnks', 'T-shirt and Tanks'),
    ('H&SS', 'Hoodies and Sweatshirts'),
    ('SW', 'Sport Wear'),
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')

)

PAYMENT_CHOICES = (
    ('E', 'eSewa'),
    ('K', 'Khalti'),
    ('C','Cash on Delivery')
)


class Item(models.Model):  # items you can purchase
    image = models.ImageField(default='default.jpg', upload_to='products')
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=10)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = RichTextUploadingField()
    date_posted = models.DateTimeField(default=timezone.now)
    video = EmbedVideoField(blank=True, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("items:product", kwargs={'slug': self.slug})

    # def get_category_url(self):
    #     return reverse('items:search_category', kwargs={'category': self.category})

    def get_add_to_cart_url(self):
        return reverse("items:add_to_cart", kwargs={'slug': self.slug})

    def get_remove_from_cart_url(self):
        return reverse("items:remove_from_cart", kwargs={'slug': self.slug})

    # def save(self, *args, **kwargs):
    #     if not 'rel' in self.video :
    #         self.video = self.video+'?rel=0' 
    #     super(Item, self).save(*args, **kwargs) 

# def pre_save_post_receiver(sender, instance, *args, **kwargs):
#     if not instance.slug:
#         instance.slug = create_slug(instance)
#
#
# pre_save.connect(pre_save_post_receiver, sender=Item)


class OrderItem(models.Model):  # when items added to cart it becomes an Ordered Item
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f'{self.quantity} of {self.item.title}'

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity*self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        else:
            return self.get_total_item_price()


class Order(models.Model):  # as shopping cart
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)  # associate order with user
    items = models.ManyToManyField(OrderItem)  # so we can add orderItems into order
    ordered = models.BooleanField(default=False)
    start_date = models.DateTimeField(auto_now_add=True)  # moment that order is created
    ordered_date = models.DateTimeField()
    # billing_address = models.ForeignKey('BillingAddress', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        # print(self.items.all())
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total


# class BillingAddress(models.Model):
#     user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
#     name = models.CharField(max_length=50, null=True, blank=True)
#     phone_number = models.CharField(max_length=11, null=True, blank=True)
#     address = models.CharField(max_length=100)
#     payment_option = models.CharField(choices=PAYMENT_CHOICES, max_length=3, default='C')

#     def __str__(self):
#         return self.user.username

templates/contact.html
{% extends 'home-page.html' %}

templates/example.html
<ul class="navbar-nav mr-auto">
	{% for category in categories %}
        <li class="nav-item">
          <a class="nav-link" href={% url 'items:search_category' category %}>{{category}}</a>
        </li>
    {% endfor } 
</ul>>        

templates/footer.html
<footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/MDBootstrap" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/mdbootstrap" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="http://codepen.io/mdbootstrap/" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

  </footer>

templates/home-page.html
{% load  static %}
{% load cart_template_tags %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
  <script>
    //new
      var user = '{{request.user}}'

      function getToken(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getToken('csrftoken');
  </script>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Django Ecommerce</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <!-- Bootstrap core CSS -->
  <link href={% static "css/bootstrap.min.css" %} rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href={% static "css/mdb.min.css" %} rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href={% static "css/style.min.css" %} rel="stylesheet">
  <link href={% static "css/style.css" %} rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }
  </style>
</head>
<body>
{% block navbar %}
  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
    <div>
      <a class="navbar-brand waves-effect" href={% url 'items:home' %}>
          <strong style="color: deepskyblue">TrendyzWear</strong>
          <div class="blue-text" style="font-size: 9px; margin-top: -3px; margin-left: 69%;">For Men</div>
      </a>

    </div>
      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item ">
            <a class="nav-link waves-effect" href="{% url 'items:home' %}">Home
{#              <span class="sr-only">(current)</span>#}
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'items:about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'items:contact' %}">Contact</a>
          </li>
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
            <li  class="nav-item">
              <a href="{% url 'items:order_summery' %}" class="nav-link waves-effect">
                <span id="cart-count" class="badge red z-depth-1"> {{request.user|cart_item_count}} </span>
                <i class="fas fa-shopping-cart" style="color: royalblue;"></i>
                <span class="clearfix d-none d-sm-inline-block"> Cart </span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
                <span class="clearfix d-none d-sm-inline-block"> Logout </span>
              </a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link waves-effect" href="{% url 'account_login' %}">
                <span class="clearfix d-none d-sm-inline-block"> Login </span>
              </a>
            </li>
            <li class="nav-item">
                <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
                  <span class="clearfix d-none d-sm-inline-block"> Sign up </span>
                </a>
            </li>
          {% endif %}
        </ul>

      </div>

    </div>
  </nav>
{% endblock %}
  <!-- Navbar -->
    <div class="mt-5">
        {% if messages %}
            {% for message in messages %}
                <span style="background-color: blue; color: white" >{{ message }}</span>
            {% endfor %}
        {% endif %}
    </div>

{% block content %}

{% endblock %}


  <!--Footer-->
  <footer class="page-footer text-center font-small mt-4 wow fadeIn" id="footer">

    <!--Call to action-->
    <div class="pt-4">

    </div>
    <!--/.Call to action-->
    <div style="display: flex; flex-direction: row; justify-content: space-evenly   " class="mb-4">
        <div>
         <div><h4>Contact</h4></div>
         <div>
             <div>Phone: 9818380761</div>
             <div>Email: srjthapa53@gmail.com</div>
             <div>Location: New Road</div>
         </div>
      </div>
        <div class="pb-4" >
          <div>
              <h5 style="margin-right: 20px">Follow US </h5>
          </div>
          <a href="#" target="_blank" style="color: darkblue;">
            <i class="fab fa-facebook mr-3 fa-2x"></i>
          </a>

          <a href="#" target="_blank" style="color: blue">
            <i class="fab fa-twitter mr-3 fa-2x"></i>
          </a>

          <a href="#" target="_blank" style="color: orangered;">
            <i class="fab fa-youtube mr-3 fa-2x"></i>
          </a>

            <a href="#" style="color: deeppink;">
            <i class="fab fa-instagram mr-3 fa-2x"></i>
          </a>

          <a href="#" target="_blank" style="color: orangered;">
            <i class="fab fa-google-plus-g mr-3 fa-2x"></i>
          </a>
        </div>
        <!-- Social icons -->
    </div>
    <!--Copyright-->
    <div class="footer-copyright py-3" style="color: white;">
      © {% now "Y" %} Copyright:
      <a href="#">TrendyzForMen.com </a>
    </div>
    <!--/.Copyright-->

  </footer>
  <!--/.Footer-->

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src={% static "js/jquery-3.4.1.min.js" %}></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src={%static "js/popper.min.js"%}></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src={% static "js/bootstrap.min.js" %}></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src={% static "js/mdb.min.js" %}></script>
  <!-- Initializations -->
  <script type="text/javascript">

       // Animations initialization
    new WOW().init();

  </script>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  <script src="{% static 'js/site.js' %}"></script>
    
    {% block extra_scripts %}
    {% endblock extra_scripts %}

</body>

</html>

templates/home.html
    {% extends 'home-page.html' %}

    {% block content %}
     <div class="searched_error ">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                  {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
            {% endfor %}
        {% endif %}
    </div>

    <!--Carousel Wrapper-->
      <div id="carousel-example-1z" class="carousel slide carousel-fade" data-ride="carousel">

        <!--Indicators-->
        <ol class="carousel-indicators">
          <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
          <li data-target="#carousel-example-1z" data-slide-to="1"></li>
          <li data-target="#carousel-example-1z" data-slide-to="2"></li>
        </ol>
        <!--/.Indicators-->

        <!--Slides-->
        <div class="carousel-inner" role="listbox">

          <!--First slide-->
          <div class="carousel-item active">
            <div class="view" style="background-image: url('https://images.pexels.com/photos/994517/pexels-photo-994517.jpeg?cs=srgb&dl=shallow-focus-photography-of-clothes-994517.jpg&fm=jpg'); background-repeat: no-repeat; background-size: cover;">

              <!-- Mask & flexbox options-->
              <div class="d-flex justify-content-center align-items-center">

              </div>
              <!-- Mask & flexbox options-->

            </div>
          </div>
          <!--/First slide-->

          <!--Second slide-->
          <div class="carousel-item">
            <div class="view" style="background-image: url('https://images.unsplash.com/photo-1562157873-818bc0726f68?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1482&q=80'); background-repeat: no-repeat; background-size: cover;">

              <!-- Mask & flexbox options-->
              <div class="d-flex justify-content-center align-items-center">

              </div>
              <!-- Mask & flexbox options-->

            </div>
          </div>
          <!--/Second slide-->

          <!--Third slide-->
          <div class="carousel-item">
            <div class="view" style="background-image: url('https://scstylecaster.files.wordpress.com/2018/12/GettyImages-914704910-copy.jpg'); background-repeat: no-repeat; background-size: cover;">

              <!-- Mask & flexbox options-->
              <div class="d-flex justify-content-center align-items-center">
              </div>
              <!-- Mask & flexbox options-->

            </div>
          </div>
          <!--/Third slide-->

        </div>
        <!--/.Slides-->

        <!--Controls-->
        <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
        <!--/.Controls-->

      </div>
      <!--/.Carousel Wrapper-->

      <!--Main layout-->
      <main>
        <div class="container">

          <!--Navbar-->
          <nav class="navbar  navbar-expand-lg navbar-dark lighten-3 mt-3 mb-5" id="secondnav">

            <!-- Navbar brand -->
            <span class="navbar-brand">Categories:</span>

            <!-- Collapse button -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
              aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Collapsible content -->
            <div class="collapse navbar-collapse" id="basicExampleNav">

              <!-- Links -->
              <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <a class="nav-link" href={% url 'items:search_category' category='all' %}>All
                    <span class="sr-only">(current)</span>
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href={% url 'items:search_category' category='S' %}>Shirts</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href={% url 'items:search_category' category='P' %}>Pants</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href={% url 'items:search_category' category='J' %}>Jeans</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href={% url 'items:search_category' category='T&Tnks' %}>T-shirt and Tanks</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href={% url 'items:search_category' category='H&SS' %}>Hoodies and Sweatshirts</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href={% url 'items:search_category' category='SW' %}>Sport Wear</a>
                </li>
              </ul>
              <!-- Links -->

              <form class="form-inline" action={% url 'items:search' %}>
                <div class="md-form my-0">
                  <input class="form-control mr-sm-2" type="number" name="max_price" placeholder="Maximum Price" aria-label="Search">
                </div>
                <button class="btn btn-outline-white btn-md my-1 my-sm-0 ml-1" type="submit">Search</button>
              </form>
            </div>
            <!-- Collapsible content -->

          </nav>
          <!--/.Navbar-->

          <!--Section: Products v.3-->
          <section class="text-center mb-4">

            <!--Grid row-->
            <div class="row wow fadeIn">
              {% for item in items %}
              <!--Grid column-->
              <div class="col-lg-3 col-md-6 mb-4">

                <!--Card-->
                <div class="card">

                  <!--Card image-->
                  <div class="view overlay">
                    <img src="{{ item.image.url }}" style="height: 285px;" class="card-img-top"
                      alt="">
                     <a href="{{ item.get_absolute_url }}">
                      <div class="mask rgba-white-slight"></div>
                    </a>
                  </div>
                  <!--Card image-->

                  <!--Card content-->
                  <div class="card-body text-center" style="height: 175px;">
                    <!--Category & Title-->
                    <a href="" class="grey-text">
                      <h5>{{item.get_category_display}}</h5>
                    </a>
                    <h5 id="title">
                      <strong>
                        <a href="{{ item.get_absolute_url }}" class="dark-grey-text" >{{item.title}}
                        </a>
                      </strong>
                    </h5>
                    <h5><span class="badge badge-pill {{item.get_label_display}}-color">NEW</span></h5>

                    <h4 class="font-weight-bold blue-text">
                      <strong>
                          {% if item.discount_price %}
                              Rs{{ item.discount_price }}
                          {% else %}
                              Rs{{ item.price }}
                          {% endif %}
                      </strong>
                    </h4>

                  </div>
                  <!--Card content-->

                </div>
                <!--Card-->

              </div>
              <!--Grid column-->
              {% endfor %}
            </div>
            <!--Grid row-->

          </section>
          <!--Section: Products v.3-->

          <!--Pagination-->
        {% if is_paginated %}
          <nav class="d-flex justify-content-center wow fadeIn">
            <ul class="pagination pg-blue">

              <!--Arrow left-->
              {% if page_obj.has_previous %}
                  <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                      <span aria-hidden="true">&laquo; PREV</span>
                      <span class="sr-only">Previous</span>
                    </a>
                  </li>
              {% else %}
                  <li class="page-item disabled" style="margin-top: 5px; color: lightgray">
                      <span aria-hidden="true">&laquo; PREV</span>
                      <span class="sr-only">Previous</span>
                  </li>
              {% endif %}
              {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                  <li class="page-item active">
                    <a class="page-link">{{ num }}
                      <span class="sr-only">(current)</span>
                    </a>
                  </li>
                {% else %}
                  <li class="page-item">
                    <a class="page-link" href="?page={{ num }}">{{ num }}
                    </a>
                  </li>
                {% endif %}
              {% endfor %}

              {% if page_obj.has_next %}
                  <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                      <span aria-hidden="true">&raquo; NEXT</span>
                      <span class="sr-only">Next</span>
                    </a>
                  </li>
              {% else %}
                  <li class="page-item disabled" style="margin-top: 5px; color: lightgray">
                      <span aria-hidden="true">&raquo; NEXT</span>
                      <span class="sr-only">Next</span>
                  </li>
            </ul>
          </nav>
        {% endif %}
          <!--Pagination-->
        {% endif %}

        </div>
      </main>
      <!--Main layout-->

    {% endblock %}

templates/items_list.html
{#{% extends 'base.html' %}#}

{#{% block contet %}#}
    <h2>Here is list of items</h2>
    {% for item in items  %}
        {{ item }}

    {% endfor %}
{#{% endblock contet %}#}

templates/new.html
Amoubt = {{ amount }}

templates/order_summery.html
{% extends 'home-page.html' %}

{% block content %}
        <div class="searched_error ">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-success alert-dismissible fade show" style="margin-bottom: -13%" role="alert">
                  {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
            {% endfor %}
        {% endif %}
    </div>
    <main>
    
        <div class="container" style="margin-top: 10%;">
          <div class="table-responsive text-nowrap ">
          <h2 class="w-50 m-auto ">Order Summery</h2 >
          <table class="table w-50 m-auto ">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Item Title</th>
                <th scope="col">Price</th>
                <th scope="col">Quantity</th>
                <th scope="col">Total Item Price</th>
              </tr>
            </thead>
            <tbody>
            {% for order_item in object.items.all %}  <!-- using OrderItem model-->
              <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{order_item.item.title}}</td>
                <td>{{order_item.item.price}}</td>
                <td>
                    <a style="color:black" href={% url 'items:remove_single_item_from_cart' order_item.item.slug %}><i class="fas fa-minus mr-2"></i></a>
                    {{order_item.quantity}}
                    <a style="color:black" href={% url 'items:add_to_cart' order_item.item.slug %}><i class="fas fa-plus ml-2"></i></a>
                </td>
                <td>
                    {% if order_item.item.discount_price %}
                        ${{ order_item.get_total_discount_item_price }}
                        <span class="badge badge-primary">saving ${{ order_item.get_amount_saved }}</span>
                    {% else %}
                        ${{ order_item.get_total_item_price }}
                    {% endif %}
                    <a style="color:red" class="text-decoration-none float-right" href={% url 'items:remove_from_cart' order_item.item.slug %}>
                        <i class="fas fa-trash"></i>
                    </a>
                </td>
              </tr>
            {% empty %}
              <tr>
                <td colspan="5">Your Cart is Empty</td>
              </tr>
              <tr>
                <td colspan="5">
                  <a class="btn btn-primary float-right" href="/">Continue Shopping</a>
                </td>
              </tr>
            {% endfor %}
            {% if object.get_total %}
                <tr>
                  <td colspan="4"><b>Order Total</b></td>
                  <td><b>${{ object.get_total }}</b></td>
                </tr>
                <tr>
                  <td colspan="5">
                      <a class="btn btn-warning float-right ml-2" href="{% url 'items:checkout' %}">Proceed to Checkout</a>
                      <a class="btn btn-primary float-right" href="/">Continue Shopping</a>
                  </td>
                </tr>
            {% endif %}

            </tbody>
          </table>
          </div>
        </div>
    </main>
{% endblock %}